
on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 14
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # 你可以根据需要修改版本号

      - name: Run your custom bash commands
        run: |
          echo "Running custom commands..."
          pwd
          ls -la
          # 替换为你自己的命令
          cd src && make && make package