
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run on ARM64 architecture
        uses: uraimo/run-on-arch-action@v2.0.1
        with:
          arch: aarch64
          distro: ubuntu2204
          installScript: |
            echo "Installing dependencies..."
            apt-get update && apt-get install -y curl git

          commandScript: |
            # 1. 设置 Node.js 14.x
            curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
            apt-get install -y nodejs
            node --version

            # 2. 设置 Go 环境（例如安装 Go 1.22）
            export GOLANG_VERSION=1.22.3
            curl -fsSL "https://golang.org/dl/go${GOLANG_VERSION}.linux-arm64.tar.gz" | tar -C /usr/local -xz
            export PATH=/usr/local/go/bin:$PATH
            go version

            # 3. 运行你的 bash 命令
            echo "Running custom commands..."
            pwd
            ls -la
            # 替换为你想运行的命令
            cd src && make && make package 